pandoc ./Compass.md                   -f markdown -t html -s -o docs/index.html
pandoc ./glossary.md                  -f markdown -t html -s -o docs/glossary.html
pandoc ./2pizzateam.md                -f markdown -t html -s -o docs/2pizzateam.html
pandoc ./3scale.md                    -f markdown -t html -s -o docs/3scale.html
pandoc ./abtest.md                    -f markdown -t html -s -o docs/abtest.html
pandoc ./adaptercontainers.md         -f markdown -t html -s -o docs/adaptercontainers.html
pandoc ./ambassadorcontainers.md      -f markdown -t html -s -o docs/ambassadorcontainers.html
pandoc ./api.md                       -f markdown -t html -s -o docs/api.html
pandoc ./apigateway.md                -f markdown -t html -s -o docs/apigateway.html
pandoc ./authentication.md            -f markdown -t html -s -o docs/authentication.html
pandoc ./batchsize.md                 -f markdown -t html -s -o docs/batchsize.html
pandoc ./bluegreen.md                 -f markdown -t html -s -o docs/bluegreen.html
pandoc ./cicd.md                      -f markdown -t html -s -o docs/cicd.html
pandoc ./circuitbreaker.md            -f markdown -t html -s -o docs/circuitbreaker.html
pandoc ./compensatingtransactions.md  -f markdown -t html -s -o docs/compensatingtransactions.html
pandoc ./configmap.md                 -f markdown -t html -s -o docs/configmap.html
pandoc ./configuration.md             -f markdown -t html -s -o docs/configuration.html
pandoc ./consistencymodels.md         -f markdown -t html -s -o docs/consistencymodels.html
pandoc ./containervirtualappliance.md -f markdown -t html -s -o docs/containervirtualappliance.html
pandoc ./cqrs.md                      -f markdown -t html -s -o docs/cqrs.html
pandoc ./cycletime.md                 -f markdown -t html -s -o docs/cycletime.html
pandoc ./darklaunch.md                -f markdown -t html -s -o docs/darklaunch.html
pandoc ./datavirtualization.md        -f markdown -t html -s -o docs/datavirtualization.html
pandoc ./devops.md                    -f markdown -t html -s -o docs/devops.html
pandoc ./discovery.md                 -f markdown -t html -s -o docs/discovery.html
pandoc ./elasticity.md                -f markdown -t html -s -o docs/elasticity.html
pandoc ./eventsourcing.md             -f markdown -t html -s -o docs/eventsourcing.html
pandoc ./eventualconsistency.md       -f markdown -t html -s -o docs/eventualconsistency.html
pandoc ./faultinjection.md            -f markdown -t html -s -o docs/faultinjection.html
pandoc ./faulttolerance.md            -f markdown -t html -s -o docs/faulttolerance.html
pandoc ./featuretoggles.md            -f markdown -t html -s -o docs/featuretoggles.html
pandoc ./glossary.md                  -f markdown -t html -s -o docs/glossary.html
pandoc ./governance.md                -f markdown -t html -s -o docs/governance.html
pandoc ./haproxy.md                   -f markdown -t html -s -o docs/haproxy.html
pandoc ./healthchecking.md            -f markdown -t html -s -o docs/healthchecking.html
pandoc ./immutableinfrastructure.md   -f markdown -t html -s -o docs/immutableinfrastructure.html
pandoc ./ingress.md                   -f markdown -t html -s -o docs/ingress.html
pandoc ./leadtime.md                  -f markdown -t html -s -o docs/leadtime.html
pandoc ./letsencrypt.md               -f markdown -t html -s -o docs/letsencrypt.html
pandoc ./logaggregation.md            -f markdown -t html -s -o docs/logaggregation.html
pandoc ./metrics.md                   -f markdown -t html -s -o docs/metrics.html
pandoc ./monitoring.md                -f markdown -t html -s -o docs/monitoring.html
pandoc ./monolith.md                  -f markdown -t html -s -o docs/monolith.html
pandoc ./nodeproxy.md                 -f markdown -t html -s -o docs/nodeproxy.html
pandoc ./orchestration.md             -f markdown -t html -s -o docs/orchestration.html
pandoc ./outlier.md                   -f markdown -t html -s -o docs/outlier.html
pandoc ./pipeline.md                  -f markdown -t html -s -o docs/pipeline.html
pandoc ./ratelimiter.md               -f markdown -t html -s -o docs/ratelimiter.html
pandoc ./rest.md                      -f markdown -t html -s -o docs/rest.html
pandoc ./ribbon.md                    -f markdown -t html -s -o docs/ribbon.html
pandoc ./route.md                     -f markdown -t html -s -o docs/route.html
pandoc ./router.md                    -f markdown -t html -s -o docs/router.html
pandoc ./rpc.md                       -f markdown -t html -s -o docs/rpc.html
pandoc ./sagas.md                     -f markdown -t html -s -o docs/sagas.html
pandoc ./serverless.md                -f markdown -t html -s -o docs/serverless.html
pandoc ./servicemesh.md               -f markdown -t html -s -o docs/servicemesh.html
pandoc ./sidecarcontainers.md         -f markdown -t html -s -o docs/sidecarcontainers.html
pandoc ./strangler.md                 -f markdown -t html -s -o docs/strangler.html
pandoc ./testing.md                   -f markdown -t html -s -o docs/testing.html
pandoc ./tracing.md                   -f markdown -t html -s -o docs/tracing.html
pandoc ./trafficsplitting.md          -f markdown -t html -s -o docs/trafficsplitting.html
