pandoc ./Compass.md                  -f markdown -t html -s -o docs/index.html
pandoc ./glossary.md                 -f markdown -t html -s -o docs/glossary.html
pandoc ./2pizzateam.md               -f markdown -t html -s -o docs/2pizzateam.html
pandoc ./3scale.md                   -f markdown -t html -s -o docs/3scale.html
pandoc ./abtest.md                   -f markdown -t html -s -o docs/abtest.html
pandoc ./adaptercontainers.md        -f markdown -t html -s -o docs/adaptercontainers.html
pandoc ./ambassadorcontainers.md     -f markdown -t html -s -o docs/ambassadorcontainers.html
pandoc ./api.md                      -f markdown -t html -s -o docs/api.html
pandoc ./apigateway.md               -f markdown -t html -s -o docs/apigateway.html
pandoc ./authentication.md           -f markdown -t html -s -o docs/authentication.html
pandoc ./batchsize.md                -f markdown -t html -s -o docs/batchsize.html
pandoc ./bluegreen.md                -f markdown -t html -s -o docs/bluegreen.html
pandoc ./cicd.md                     -f markdown -t html -s -o docs/cicd.html
pandoc ./circuitbreaker.md           -f markdown -t html -s -o docs/circuitbreaker.html
pandoc ./compensatingtransactions.md -f markdown -t html -s -o docs/compensatingtransactions.html
pandoc ./configmap.md                -f markdown -t html -s -o docs/configmap.html
pandoc ./adaptercontainers.md -f markdown -t html -s -o docs/adaptercontainers.html
pandoc ./adaptercontainers.md -f markdown -t html -s -o docs/adaptercontainers.html
pandoc ./adaptercontainers.md -f markdown -t html -s -o docs/adaptercontainers.html
pandoc ./adaptercontainers.md -f markdown -t html -s -o docs/adaptercontainers.html
pandoc ./adaptercontainers.md -f markdown -t html -s -o docs/adaptercontainers.html
pandoc ./adaptercontainers.md -f markdown -t html -s -o docs/adaptercontainers.html
